name: Bug Report
description: Report a bug in claude-code-plugins
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug. Please fill out the sections below.

  - type: dropdown
    id: plugin
    attributes:
      label: Plugin
      description: Which plugin is affected?
      options:
        - core
        - notifications
        - frameworks-frontend
        - frameworks-backend
        - frameworks-shared
        - task-master
        - mcp-servers
        - installer
        - other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of the bug.
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Run '...'
        2. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: OS, Claude Code version, shell.
      placeholder: |
        - OS: Ubuntu 24.04
        - Claude Code: 1.0.0
        - Shell: bash 5.2
    validations:
      required: false
